-- 000005_tenant_not_null.down.sql
-- Rollback Step 3: Hapus constraint NOT NULL

ALTER TABLE orders ALTER COLUMN tenant_id DROP NOT NULL;
ALTER TABLE orders ALTER COLUMN tenant_id DROP DEFAULT;
ALTER TABLE orders ALTER COLUMN store_id DROP NOT NULL;
ALTER TABLE orders ALTER COLUMN store_id DROP DEFAULT;

ALTER TABLE menus ALTER COLUMN tenant_id DROP NOT NULL;
ALTER TABLE menus ALTER COLUMN tenant_id DROP DEFAULT;
ALTER TABLE menus ALTER COLUMN store_id DROP NOT NULL;
ALTER TABLE menus ALTER COLUMN store_id DROP DEFAULT;

ALTER TABLE users ALTER COLUMN tenant_id DROP NOT NULL;
ALTER TABLE users ALTER COLUMN tenant_id DROP DEFAULT;
ALTER TABLE users ALTER COLUMN store_id DROP NOT NULL;
ALTER TABLE users ALTER COLUMN store_id DROP DEFAULT;
